http: 
  listener: 
    host: "0.0.0.0"
    port: "8081"
  requester: 
    customer: 
      papi: 
        host: "customer-papi-app-aman-v1.us-e2.cloudhub.io"
        pathCustomerState: "/api/customerState"
        port: ""   
    verification:
      papi:
        host: "customer-papi-app-aman-v1.us-e2.cloudhub.io"
        pathVerification: "/api/verification"
        port: ""
    registration:
      papi:
        host: "customer-papi-app-aman-v1.us-e2.cloudhub.io"
        pathRegistration: "api/customers/registration"
        port: "" 
instanceID: "17815796"